import type { NextPage } from 'next'
import Head from 'next/head'
import Categories from '../components/Categories';
import MainHeader from '../components/MainHeader';
import NotesList from '../components/Notes';
import styles from './Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tech Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <div className={styles.frame}>
        <section className={styles.sectionCategories}>
          <Categories values={[
            { id: '1', caption: 'C#', link: '#' },
            { id: '2', caption: 'JavaScript', link: '#' },
            { id: '3', caption: 'Rust', link: '#' },
            { id: '4', caption: 'Utils', link: '#' },
            { id: '5', caption: 'Vim', link: '#' },
            { id: '6', caption: 'Algorithms', link: '#' },
          ]} />
        </section>
        <main className={styles.sectionMain}>
          <MainHeader title='Tech Notes' />
          <NotesList values={[
            {
              id: 1,
              link: '#',
              title: 'AutoFixture In C#',
              description: 'AutoFixture testing strategies in C#',
            },
            {
              id: 2,
              link: '#',
              title: 'JavaScript Events',
              description: 'JS events basics',
            },
            {
              id: 3,
              link: '#',
              title: 'Rust Useful Traits',
              description: 'List of good to know common traits in Rust',
            },
            {
              id: 4,
              link: '#',
              title: 'Creating C# CLI App',
              description: 'Simple example of C# CLI application with Microsoft.Extensions.CommandLineUtils, MediatR and Serilog',
            },
            {
              id: 6,
              link: '#',
              title: 'Asp.Net Core Project Configuration',
              description: 'Configuration of Asp.Net Core project runtime Lorem ipsum dolor sit amet consectetur adipisicing elit.Nihil quo ipsa repudiandae doloribus minima, sunt hic quae atque rerum? Qui eum commodi quam dolores minima quae odit unde asperiores adipisci.Lorem ipsum dolor sit amet, consectetur adipisicing elit.Veniam expedita debitis, cumque magnam dolor itaque blanditiis porro iure at, ad pariatur reprehenderit libero odio, accusantium ab labore nam? Laboriosam, blanditiis.',
            },
          ]} />
        </main>
      </div>
    </>
  )
}

export default Home
